apiVersion: v1
kind: Service
metadata:
  namespace: pokeclicker
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pokeclicker
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pokeclicker/backend:latest
          ports:
            - containerPort: 8888
          env:
            - name: pokeclicker_environment
              value: "prod"
            - name: sentry_dsn
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: sentry_dsn
            - name: backend_port
              value: "8888"
            - name: db_host
              value: "mysql"
            - name: db_port
              value: "3306"
            - name: db_name
              value: "pokeclicker"
            - name: db_username
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: db_username
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: db_password
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: db_root_password
            - name: redis_master_host
              value: "redis-master"
            - name: redis_master_port
              value: "6379"
            - name: redis_slave_host
              value: "redis-slave"
            - name: redis_slave_port
              value: "6379"
