apiVersion: v1
kind: Service
metadata:
  namespace: pokeclicker
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pokeclicker
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pokeclicker/frontend:latest
          ports:
            - containerPort: 80
